config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  namespace :home do
    post :near_houses
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/earth.rb
module Earth extend self

  RADIUS = 6371 * 1000

end

app/models/house.rb
class House < ApplicationRecord
  validates :address, presence: true, uniqueness: true
  validates :lat, presence: true, numericality: {greater_than_or_equal_to: Moscow::min_lat, less_than_or_equal_to: Moscow::max_lat}
  validates :long, presence: true, numericality: {greater_than_or_equal_to: Moscow::min_long, less_than_or_equal_to: Moscow::max_long}

  def self.near point:, radius: 4_000
    all.map {|h| {instance: h, distance: distance(h, point)}}
       .select {|o| o[:distance] <= radius}
       .sort_by {|o| o[:distance]}
  end

  ##
  # gets distance between to points by coordinates
  # using https://en.wikipedia.org/wiki/Haversine_formula
  def self.distance p1, p2
    k = Math::PI / 180
    pr1, pr2 = [p1, p2].map {|p| {lat: p[:lat] * k, long: p[:long] * k} }

    n = Math.sin((pr2[:lat] - pr1[:lat]) / 2) ** 2 + \
        Math.cos(pr1[:lat]) * Math.cos(pr1[:lat]) * \
        Math.sin((pr2[:long] - pr1[:long]) / 2) ** 2
    c = 2 * Math::atan2(Math::sqrt(n), Math::sqrt(1 - n))

    (Earth::RADIUS * c).to_i
  end
end

app/models/moscow.rb
module Moscow extend self
  COORDS = {
    lat: 55.75583,
    long: 37.61778,
    range_lat: 0.057147,
    range_long: 0.117635,
  }.freeze

  def point
    {
      lat: rand(min_lat..max_lat).round(6),
      long: rand(min_long..max_long).round(6),
    }
  end

  def min_lat
    COORDS[:lat] - COORDS[:range_lat]
  end

  def max_lat
    COORDS[:lat] + COORDS[:range_lat]
  end

  def min_long
    COORDS[:long] - COORDS[:range_long]
  end

  def max_long
    COORDS[:long] + COORDS[:range_long]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :verify_authenticity_token, :only => [:near_houses]


  def index
  end

  def near_houses
    @alerts = []
    response = {}
    houses = nil
    response[:alerts] << "no point parameters passed" unless (params[:lat] and params[:long])

    begin
      point = {lat: params[:lat].to_f, long: params[:long].to_f}
      houses = House::near(point: point)
      response[:houses] = houses
    rescue StandardError => err
      @alerts << err.message
    end

    response[:html] = render_to_string partial: "home/house_list", locals: {houses: houses}, :format => :html
    render json: response.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_house_list.html.erb
<% if @alerts.present? %>
  <div class="alerts">
    <% @alerts.each do |a| %>
      <div class="alert warning"><%= a %></div>
    <% end %>
  </div>
<% end %>


<% if houses.present? %>
  <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th>Address</th>
        <th>Distance, m</th>
      </tr>
    </thead>
    <tbody>
      <% houses.each do |h| %>
        <tr>
          <td><%= h[:instance][:address] %></td>
          <td><%= h[:distance] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info">No houses in the area</div>
<% end %>

app/views/home/index.html.erb
<!-- <h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p> -->


<div id="map" style="width: 850px; height: 420px">
</div>

<div class="results js-results" style="width: 850px"></div>

<script type="text/ecmascript">
  ;(function (w, $) {
    if (w.locator.Map) {
      let map = new w.locator.Map({
        lat: <%= Moscow::COORDS[:lat] %>,
        long: <%= Moscow::COORDS[:long] %>
      }, "<%= home_near_houses_path %>")

      ymaps.ready(map.addMap.bind(map));
    } else {
      throw "Locator Map class not found!"
    }
  })(window, jQuery);

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Locator</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://api-maps.yandex.ru/2.1/?apikey=<%= ENV['YANDEX_GEOCODER_TOKEN']%>&lang=ru_RU" type="text/javascript">
    </script>
  </head>

  <body class="text-center controller-<%= controller_name %> action-<%= action_name %>">
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead">
        <div class="inner">
          <h3 class="masthead-brand">Locator</h3>
        </div>
      </header>

      <main role="main" class="inner cover">
        <%= yield %>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          Copyright OM 2019. All rights are right :)
        </div>
      </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

</body></html>